//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRS
    {
        public int Id { get; set; }
        public string Nim { get; set; }
        public string Kode { get; set; }
    
        public virtual Mahasiswa Mahasiswa { get; set; }
        public virtual Matakuliah Matakuliah { get; set; }
    }
}
