//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mahasiswa()
        {
            this.KRS = new HashSet<KRS>();
        }
    
        public string Nim { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
        public double IPK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRS> KRS { get; set; }
    }
}
